cke_placeholder.settings:
  type: mapping
  label: Settings
  mapping:
    cke_placeholder_allowed_extensions:
      type: string
    cke_placeholder_filter_regex:
      type: string
    cke_placeholder_items_per_page:
      type: integer
